### ISSUE TITLE
Fix relative imports

### ISSUE THREAD

**Issue by romanstrazanec** [romanstrazanec/algorithms#1]
When importing a file from the current directory, PyCharm IDE also VSCode shows error, but running the file with fixed error raises ModuleNotFoundError.

`from module import function` -> IDE error

Relative import:

`from .module import function` -> raises ModuleNotFoundError

Possible solution by creating virtual environment.

**Comment by patriktariska** [comment]
**Bug was fixed with the installation of [virtual environment](https://docs.python.org/3/tutorial/venv.html).**

Package, the whole _algorithms_ folder, has to be imported into _lib_ folder that is created with the Venv or included in _lib_ folder in the general system's Python path.

**Comment by romanstrazanec** [comment]
https://stackoverflow.com/questions/21236824/unresolved-reference-issue-in-pycharm
